#PBS -N binary2cat
#PBS -l nodes=1:gpus=1:S
#PBS -r y



export LD_LIBRARY_PATH=/home/liyh/lib/cuda/lib64:$LD_LIBRARY_PATH
export CUDNN_ROOT=/home/liyh/lib/cuda
export C_INCLUDE_PATH=/home/liyh/lib/cuda/include:$C_INCLUDE_PATH
export PATH=/opt/cuda:$PATH
export LD_LIBRARY_PATH=/opt/cuda/lib64:$LD_LIBRARY_PATH
export PATH=/home/liyh/anaconda2/bin:$PATH


cd /data12/liyh/projects/pix2pix-tensorflow

err_f=/data1/liyh/Cat_original/binary/combined_augmented/checkpoints/crop_flip/err_file.err
log_f=/data1/liyh/Cat_original/binary/combined_augmented/checkpoints/crop_flip/out_file.log

echo Time is 'data'
echo Directory is $PWD
echo This job runs on:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

python pix2pix.py \
 --mode train \
 --output_dir /data1/liyh/Cat_original/binary/combined_augmented/checkpoints/crop_flip \
 --max_epochs 2000 \
 --input_dir /data1/liyh/Cat_original/binary/combined_augmented/train  \
 --which_direction BtoA \
 --batch_size 16 >$log_f 2>$err_f